// Worldwide currency list — Israel and ILS intentionally excluded.
export interface CurrencyOption {
  country: string;
  code: string;
  symbol: string;
}

export const CURRENCIES: CurrencyOption[] = [
  { country: "United States", code: "USD", symbol: "$" },
  { country: "Pakistan", code: "PKR", symbol: "₨" },
  { country: "United Kingdom", code: "GBP", symbol: "£" },
  { country: "European Union", code: "EUR", symbol: "€" },
  { country: "India", code: "INR", symbol: "₹" },
  { country: "United Arab Emirates", code: "AED", symbol: "د.إ" },
  { country: "Saudi Arabia", code: "SAR", symbol: "﷼" },
  { country: "Qatar", code: "QAR", symbol: "ر.ق" },
  { country: "Kuwait", code: "KWD", symbol: "د.ك" },
  { country: "Bahrain", code: "BHD", symbol: ".د.ب" },
  { country: "Oman", code: "OMR", symbol: "ر.ع." },
  { country: "Turkey", code: "TRY", symbol: "₺" },
  { country: "Egypt", code: "EGP", symbol: "ج.م" },
  { country: "Morocco", code: "MAD", symbol: "د.م." },
  { country: "Algeria", code: "DZD", symbol: "د.ج" },
  { country: "Tunisia", code: "TND", symbol: "د.ت" },
  { country: "Jordan", code: "JOD", symbol: "د.أ" },
  { country: "Lebanon", code: "LBP", symbol: "ل.ل" },
  { country: "Iraq", code: "IQD", symbol: "ع.د" },
  { country: "Iran", code: "IRR", symbol: "﷼" },
  { country: "Afghanistan", code: "AFN", symbol: "؋" },
  { country: "Bangladesh", code: "BDT", symbol: "৳" },
  { country: "Sri Lanka", code: "LKR", symbol: "Rs" },
  { country: "Nepal", code: "NPR", symbol: "रू" },
  { country: "Bhutan", code: "BTN", symbol: "Nu." },
  { country: "Maldives", code: "MVR", symbol: "Rf" },
  { country: "China", code: "CNY", symbol: "¥" },
  { country: "Japan", code: "JPY", symbol: "¥" },
  { country: "South Korea", code: "KRW", symbol: "₩" },
  { country: "North Korea", code: "KPW", symbol: "₩" },
  { country: "Mongolia", code: "MNT", symbol: "₮" },
  { country: "Hong Kong", code: "HKD", symbol: "HK$" },
  { country: "Taiwan", code: "TWD", symbol: "NT$" },
  { country: "Singapore", code: "SGD", symbol: "S$" },
  { country: "Malaysia", code: "MYR", symbol: "RM" },
  { country: "Indonesia", code: "IDR", symbol: "Rp" },
  { country: "Philippines", code: "PHP", symbol: "₱" },
  { country: "Thailand", code: "THB", symbol: "฿" },
  { country: "Vietnam", code: "VND", symbol: "₫" },
  { country: "Cambodia", code: "KHR", symbol: "៛" },
  { country: "Laos", code: "LAK", symbol: "₭" },
  { country: "Myanmar", code: "MMK", symbol: "K" },
  { country: "Brunei", code: "BND", symbol: "B$" },
  { country: "Australia", code: "AUD", symbol: "A$" },
  { country: "New Zealand", code: "NZD", symbol: "NZ$" },
  { country: "Fiji", code: "FJD", symbol: "FJ$" },
  { country: "Papua New Guinea", code: "PGK", symbol: "K" },
  { country: "Canada", code: "CAD", symbol: "C$" },
  { country: "Mexico", code: "MXN", symbol: "Mex$" },
  { country: "Brazil", code: "BRL", symbol: "R$" },
  { country: "Argentina", code: "ARS", symbol: "$" },
  { country: "Chile", code: "CLP", symbol: "$" },
  { country: "Colombia", code: "COP", symbol: "$" },
  { country: "Peru", code: "PEN", symbol: "S/" },
  { country: "Venezuela", code: "VES", symbol: "Bs." },
  { country: "Uruguay", code: "UYU", symbol: "$U" },
  { country: "Paraguay", code: "PYG", symbol: "₲" },
  { country: "Bolivia", code: "BOB", symbol: "Bs." },
  { country: "Ecuador", code: "USD", symbol: "$" },
  { country: "Costa Rica", code: "CRC", symbol: "₡" },
  { country: "Panama", code: "PAB", symbol: "B/." },
  { country: "Guatemala", code: "GTQ", symbol: "Q" },
  { country: "Honduras", code: "HNL", symbol: "L" },
  { country: "Nicaragua", code: "NIO", symbol: "C$" },
  { country: "Cuba", code: "CUP", symbol: "$" },
  { country: "Dominican Republic", code: "DOP", symbol: "RD$" },
  { country: "Jamaica", code: "JMD", symbol: "J$" },
  { country: "Trinidad and Tobago", code: "TTD", symbol: "TT$" },
  { country: "Switzerland", code: "CHF", symbol: "CHF" },
  { country: "Norway", code: "NOK", symbol: "kr" },
  { country: "Sweden", code: "SEK", symbol: "kr" },
  { country: "Denmark", code: "DKK", symbol: "kr" },
  { country: "Iceland", code: "ISK", symbol: "kr" },
  { country: "Poland", code: "PLN", symbol: "zł" },
  { country: "Czech Republic", code: "CZK", symbol: "Kč" },
  { country: "Hungary", code: "HUF", symbol: "Ft" },
  { country: "Romania", code: "RON", symbol: "lei" },
  { country: "Bulgaria", code: "BGN", symbol: "лв" },
  { country: "Croatia", code: "EUR", symbol: "€" },
  { country: "Serbia", code: "RSD", symbol: "дин" },
  { country: "Ukraine", code: "UAH", symbol: "₴" },
  { country: "Russia", code: "RUB", symbol: "₽" },
  { country: "Belarus", code: "BYN", symbol: "Br" },
  { country: "Kazakhstan", code: "KZT", symbol: "₸" },
  { country: "Uzbekistan", code: "UZS", symbol: "сўм" },
  { country: "Azerbaijan", code: "AZN", symbol: "₼" },
  { country: "Georgia", code: "GEL", symbol: "₾" },
  { country: "Armenia", code: "AMD", symbol: "֏" },
  { country: "South Africa", code: "ZAR", symbol: "R" },
  { country: "Nigeria", code: "NGN", symbol: "₦" },
  { country: "Kenya", code: "KES", symbol: "KSh" },
  { country: "Ghana", code: "GHS", symbol: "₵" },
  { country: "Ethiopia", code: "ETB", symbol: "Br" },
  { country: "Tanzania", code: "TZS", symbol: "TSh" },
  { country: "Uganda", code: "UGX", symbol: "USh" },
  { country: "Rwanda", code: "RWF", symbol: "FRw" },
  { country: "Zambia", code: "ZMW", symbol: "ZK" },
  { country: "Zimbabwe", code: "ZWL", symbol: "Z$" },
  { country: "Botswana", code: "BWP", symbol: "P" },
  { country: "Namibia", code: "NAD", symbol: "N$" },
  { country: "Mozambique", code: "MZN", symbol: "MT" },
  { country: "Angola", code: "AOA", symbol: "Kz" },
  { country: "Sudan", code: "SDG", symbol: "ج.س." },
  { country: "Libya", code: "LYD", symbol: "ل.د" },
  { country: "Senegal", code: "XOF", symbol: "CFA" },
  { country: "Ivory Coast", code: "XOF", symbol: "CFA" },
  { country: "Cameroon", code: "XAF", symbol: "FCFA" },
];

export const findCurrency = (code: string) =>
  CURRENCIES.find((c) => c.code === code) || CURRENCIES[0];
